spring :
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://db-4s5bv.pub-cdb.ntruss.com:3306/support-connection?serverTimezone=UTC&characterEncoding=UTF-8
    username : #username
    password: #passwd

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    format_sql: true
    ddl-auto: create

  http:
    encoding-charset : UTF-8
    encoding-enabled : true
    encoding:-force : true


server :
  port : 8001

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
